apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2pv
  labels:
    assign-to: "data-stor"
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.177.149.110 
    path: /nfs2/gcdb2
