create table items
(
 id INTEGER NOT NULL,
 name VARCHAR(100) NOT NULL,
 description VARCHAR(1500),
 price DECIMAL(8,2),
 img_alt VARCHAR(100),
 img VARCHAR(100),
 quantity DECIMAL,
 CREATIONDATE TIMESTAMP,
 UPDATEDATE TIMESTAMP

);
COMMIT;
