create table items
(
 id INTEGER NOT NULL,
 name VARCHAR(300) NOT NULL,
 description VARCHAR(5000),
 price DECIMAL(8,2),
 img_alt VARCHAR(200),
 img VARCHAR(200),
 quantity DECIMAL,
 CREATIONDATE TIMESTAMP,
 UPDATEDATE TIMESTAMP

);
COMMIT;
